





// (header>a+img)+(nav>ul>li*5>a)+(main>hi+div*3)+(footer>div*2>ul> >a)

<header>
    <a href=""></a>
    <img src="" alt="" />
</header>
<nav>
    <ul>
        <li><a href=""></a></li>
        <li><a href=""></a></li>
        <li><a href=""></a></li>
        <li><a href=""></a></li>
        <li><a href=""></a></li>
    </ul>
</nav>
<main>
    <hi></hi>
    <div></div>
    <div></div>
    <div></div>
</main>
<footer>
    <div>
        <ul>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
        </ul>
    </div>
    <div>
        <ul>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
        </ul>
    </div>
</footer>



