version: '3.8'

services:
  stiven:
    image: mysql:8.0-debian
    ports:
      - "3306:3306"
    container_name: stiven
    restart: always
    volumes:
      - ./data_stiven_mysql:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=MinhaSenhaSegura123
      - MYSQL_DATABASE=LIVROS

volumes:
  data_stiven_mysql:
